(function () {
  const templates = {
    dashboard: `
      <section class="panel">
        <h2 id="companyName">Carregando...</h2>
        <p class="muted" id="userName"></p>
        <p class="message" id="homeMessage"></p>
      </section>
      <section class="panel" id="dashboardSummary"></section>
    `,
    settings: `
      <p class="muted" id="settingsCompanyName">Carregando...</p>
      <nav class="tabs" aria-label="Configurações">
        <button class="tab active" data-tab="companySection" type="button">Empresa</button>
        <button class="tab" data-tab="brandingSection" type="button">Identidade</button>
        <button class="tab" data-tab="settingsSection" type="button">Oficina</button>
        <button class="tab" data-tab="hoursSection" type="button">Horários</button>
        <button class="tab" data-tab="integrationsSection" type="button">Integrações</button>
      </nav>
      <section class="panel section active" id="companySection"><h2>Dados da empresa</h2><form id="companyForm" class="grid"><label>Nome legal<input name="legalName"></label><label>Nome comercial<input name="tradeName"></label><label>NIF<input name="taxNumber"></label><label>E-mail<input name="email" type="email"></label><label>Telefone<input name="phone"></label><label>WhatsApp<input name="whatsapp"></label><label>Cidade<input name="city"></label><label>País<input name="country"></label><label>Timezone<input name="timezone"></label><label>Locale<input name="locale"></label><label>Moeda<input name="currency" maxlength="3"></label><label>Símbolo<input name="currencySymbol"></label><label>Endereço<textarea name="address"></textarea></label><div class="actions"><button type="submit">Salvar empresa</button></div></form></section>
      <section class="panel section" id="brandingSection"><h2>Identidade visual</h2><form id="brandingForm" class="grid"><label>Logo URL<input name="logoUrl" type="url"></label><label>Favicon URL<input name="faviconUrl" type="url"></label><label>Imagem de login<input name="loginImageUrl" type="url"></label><label>Imagem do painel<input name="dashboardImageUrl" type="url"></label><label>Cor principal<input name="primaryColor" placeholder="#7C3AED"></label><label>Cor secundária<input name="secondaryColor" placeholder="#111827"></label><label>Cor de destaque<input name="accentColor" placeholder="#22D3EE"></label><label>Tema<select name="theme"><option value="dark">dark</option><option value="light">light</option><option value="system">system</option></select></label><div class="actions"><button type="submit">Salvar identidade</button></div></form></section>
      <section class="panel section" id="settingsSection"><h2>Configurações da oficina</h2><form id="workshopForm" class="grid-3"><label>Abre sábado<select name="worksSaturday"><option value="true">Sim</option><option value="false">Não</option></select></label><label>Abre domingo<select name="worksSunday"><option value="false">Não</option><option value="true">Sim</option></select></label><label>Duração padrão<input name="defaultServiceDurationMinutes" type="number" min="1"></label><label>Intervalo agenda<input name="appointmentIntervalMinutes" type="number" min="1"></label><label>Prefixo OS<input name="workOrderPrefix" maxlength="10"></label><label>Próxima OS<input name="workOrderNextNumber" type="number" min="1"></label><label>Dígitos OS<input name="workOrderNumberPadding" type="number" min="3" max="12"></label><label>IVA padrão<input name="defaultTaxPercentage" type="number" min="0" max="100" step="0.01"></label><label>Margem peças<input name="defaultPartsMarginPercentage" type="number" min="0" max="100" step="0.01"></label><label>Aprovação cliente<select name="requireCustomerApproval"><option value="true">Sim</option><option value="false">Não</option></select></label><label>Fotos do veículo<select name="requireVehiclePhotos"><option value="false">Não</option><option value="true">Sim</option></select></label><label>Checklist<select name="requireChecklist"><option value="true">Sim</option><option value="false">Não</option></select></label><div class="actions"><button type="submit">Salvar configurações</button></div></form></section>
      <section class="panel section" id="hoursSection"><h2>Horários</h2><form id="hoursForm"><div id="hoursList"></div><div class="actions"><button type="submit">Salvar horários</button></div></form></section>
      <section class="panel section" id="integrationsSection"><h2>Integrações futuras</h2><div id="integrationsList"></div></section>
      <p class="message" id="settingsMessage"></p>
    `,
    users: `
      <section class="panel stack"><div class="toolbar"><input id="search" placeholder="Pesquisar"><select id="status"><option value="">Todos</option><option value="active">Ativos</option><option value="inactive">Inativos</option><option value="blocked">Bloqueados</option></select><button id="loadButton">Filtrar</button></div><form id="userForm" class="grid"><input type="hidden" name="id"><label>Nome<input name="name" required></label><label>E-mail<input name="email" type="email" required></label><label>Username<input name="username"></label><label>Telefone<input name="phone"></label><label>Setor<select name="sectorId"></select></label><label>Perfil<select name="roleId"></select></label><label>Status<select name="status"><option value="active">active</option><option value="inactive">inactive</option><option value="blocked">blocked</option></select></label><label>Senha temporária<input name="password" type="password"></label><div class="actions"><button type="submit">Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="usersTable"></div><div id="historyPanel"></div><p class="message" id="pageMessage"></p></section>
    `,
    sectors: `<section class="panel stack"><form id="sectorForm" class="grid"><input type="hidden" name="id"><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Ordem<input name="displayOrder" type="number" value="0"></label><label>Status<select name="status"><option value="active">active</option><option value="inactive">inactive</option></select></label><label>Descrição<textarea name="description"></textarea></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="sectorsTable"></div><p class="message" id="pageMessage"></p></section>`,
    roles: `<section class="panel stack"><form id="roleForm" class="grid"><input type="hidden" name="id"><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Ordem<input name="displayOrder" type="number" value="0"></label><label>Status<select name="status"><option value="active">active</option><option value="inactive">inactive</option></select></label><label>Descrição<textarea name="description"></textarea></label><div class="actions"><button>Salvar perfil</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="rolesTable"></div><section><h2>Permissões do perfil selecionado</h2><div id="permissionsList" class="checkbox-grid"></div><div class="actions"><button id="savePermissions">Salvar permissões</button></div></section><p class="message" id="pageMessage"></p></section>`,
    audit: `<section class="panel stack"><div class="toolbar"><input id="action" placeholder="Ação"><input id="entity" placeholder="Entidade"><button id="loadButton">Filtrar</button></div><div id="auditTable"></div><pre class="panel" id="auditDetails"></pre><p class="message" id="pageMessage"></p></section>`,
    "workshop-map": `<section class="panel"><div id="mapSummary" class="map-summary"></div><div id="mapAreas" class="stack"></div><p class="message" id="pageMessage"></p></section>`,
    "workshop-areas": `<section class="panel stack"><form id="areaForm" class="grid"><input type="hidden" name="id"><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Ordem<input name="displayOrder" type="number" value="0"></label><label>Status<select name="status"><option value="active">active</option><option value="inactive">inactive</option></select></label><label>Descrição<textarea name="description"></textarea></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="areasTable"></div><p class="message" id="pageMessage"></p></section>`,
    "workshop-bays": `<section class="panel stack"><form id="bayForm" class="grid"><input type="hidden" name="id"><label>Área<select name="areaId"></select></label><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Tipo<select name="bayType"><option value="general">general</option><option value="lift">lift</option><option value="alignment">alignment</option><option value="balancing">balancing</option><option value="diagnostics">diagnostics</option><option value="electrical">electrical</option><option value="washing">washing</option><option value="parking">parking</option><option value="other">other</option></select></label><label>Estado<select name="operationalStatus"><option value="available">available</option><option value="reserved">reserved</option><option value="occupied">occupied</option><option value="maintenance">maintenance</option><option value="unavailable">unavailable</option></select></label><label>Cor<input name="color" placeholder="#7C3AED"></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="baysTable"></div><div id="historyPanel"></div><p class="message" id="pageMessage"></p></section>`,
    "equipment-types": `<section class="panel stack"><form id="typeForm" class="grid"><input type="hidden" name="id"><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Intervalo manutenção<input name="defaultMaintenanceIntervalDays" type="number"></label><label>Status<select name="status"><option value="active">active</option><option value="inactive">inactive</option></select></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="typesTable"></div><p class="message" id="pageMessage"></p></section>`,
    equipment: `<section class="panel stack"><form id="equipmentForm" class="grid"><input type="hidden" name="id"><label>Tipo<select name="equipmentTypeId"></select></label><label>Baia<select name="bayId"></select></label><label>Nome<input name="name" required></label><label>Código<input name="code"></label><label>Patrimônio<input name="assetNumber"></label><label>Estado<select name="operationalStatus"><option value="available">available</option><option value="in_use">in_use</option><option value="maintenance">maintenance</option><option value="unavailable">unavailable</option><option value="retired">retired</option></select></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="equipmentTable"></div><div id="historyPanel"></div><p class="message" id="pageMessage"></p></section>`,
    "equipment-maintenance": `<section class="panel stack"><form id="maintenanceForm" class="grid"><input type="hidden" name="id"><label>Equipamento<select name="equipmentId"></select></label><label>Tipo<select name="maintenanceType"><option value="preventive">preventive</option><option value="corrective">corrective</option><option value="inspection">inspection</option><option value="calibration">calibration</option><option value="other">other</option></select></label><label>Data<input name="scheduledDate" type="date" required></label><label>Custo<input name="cost" type="number" step="0.01"></label><label>Descrição<textarea name="description"></textarea></label><div class="actions"><button>Salvar</button><button type="button" class="secondary" id="clearButton">Limpar</button></div></form><div id="maintenanceTable"></div><p class="message" id="pageMessage"></p></section>`
  };

  function render(pageId, container) {
    container.textContent = "";
    const template = document.createElement("template");
    template.innerHTML = templates[pageId] || templates.dashboard;
    container.appendChild(template.content.cloneNode(true));
  }

  window.DOZEMECPageTemplates = { render };
})();
